//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulacion1
    {
        public int IdPostulacion { get; set; }
        public int IdSolicitante { get; set; }
        public Nullable<int> IdOferta { get; set; }
        public Nullable<System.DateTime> FechaPostulacion { get; set; }
        public Nullable<int> IdEstadoPostulacion { get; set; }
    }
}
